version: '3.1'
services:
  mongo:
    image: mongo:6
    container_name: unbreakable-db
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
