version: '3.1'
services:
  mongo:
    image: mongo:6
    container_name: unbreakable-db
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - default

  app:
    image: unbreakable-app
    container_name: unbreakable-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3333:3000"
    depends_on:
      - mongo
    links:
      - mongo
    command: npm start
    networks:
      - default

networks:
  default:
    driver: bridge
 